recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    log_rating,
    RecipeDetailView,
    RecipeListView,
    ShoppingListView,
    ShoppingItemCreate,
    ShoppingListDelete,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path("shopping_items/", ShoppingListView.as_view(), name="shopping_list"),
    path("shopping_items/create/", ShoppingItemCreate, name="shopping_new"),
    path("shopping_items/delete/", ShoppingListDelete, name="shopping_delete"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("mealplans/", include("mealplans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

recipes/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL,
        related_name="recipes",
        on_delete=models.CASCADE,
        null=True,
    )
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    servings = models.PositiveSmallIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(100),
        ]
    )

    def __str__(self):
        return self.name + " by " + str(self.author)


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField(validators=[MaxValueValidator(9999)])
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ingredients",
        on_delete=models.CASCADE,
    )
    measure = models.ForeignKey("Measure", on_delete=models.PROTECT)
    food = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def __str__(self):
        amount = str(self.amount)
        measure = self.measure.name
        food = self.food.name
        return amount + " " + measure + " " + food


class Step(models.Model):
    recipe = models.ForeignKey(
        "Recipe",
        related_name="steps",
        on_delete=models.CASCADE,
    )
    order = models.PositiveSmallIntegerField()
    directions = models.CharField(max_length=300)
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return str(self.order) + ". " + self.directions


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ratings",
        on_delete=models.CASCADE,
    )


class ShoppingItem(models.Model):
    user = models.ForeignKey(
        USER_MODEL,
        related_name="ShoppingItem",
        on_delete=models.CASCADE,
        null=True,
    )
    food_item = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def __str__(self):
        return str(self.food_item) + " for " + str(self.user)

recipes/forms.py
from django import forms
from recipes.models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "name",
            "author",
            "description",
            "image",
        ]


from recipes.models import Rating


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]

recipes/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.db import IntegrityError

from recipes.forms import RatingForm
from recipes.models import Recipe, ShoppingItem, Ingredient

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods


def log_rating(request, recipe_id):
    try:
        if request.method == "POST":
            form = RatingForm(request.POST)
            if form.is_valid():
                rating = form.save(commit=False)
                rating.recipe = Recipe.objects.get(pk=recipe_id)
                rating.save()
    except Recipe.DoesNotExist:
        return redirect("recipes_list")
    return redirect("recipe_detail", pk=recipe_id)


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 6
    sort_method = "-updated"

    def post(self, request):
        self.sort_method = request.POST.get("sort_type")
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_queryset(self):
        return Recipe.objects.order_by(self.sort_method)


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"
    current_serving_size = Recipe.servings

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()

        shopping_items = [
            item.food_item for item in self.request.user.ShoppingItem.all()
        ]

        context["shopping_list_foods"] = shopping_items
        context["current_serving_size"] = Recipe.servings

        return context

    def post(self, request, **kwargs):
        self.current_serving_size = request.POST.get("serving_scaling")
        self.object = self.get_object()
        context = self.get_context_data(**kwargs)
        context["current_serving_size"] = self.current_serving_size
        return self.render_to_response(context)


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = ["name", "description", "image", "servings"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = ["name", "description", "image", "servings"]

    def get_success_url(self):
        recipeid = self.kwargs["pk"]
        return reverse_lazy("recipe_detail", kwargs={"pk": recipeid})

    def get_queryset(self):
        return Recipe.objects.filter(author=self.request.user)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")

    def get_queryset(self):
        return Recipe.objects.filter(author=self.request.user)


class ShoppingListView(LoginRequiredMixin, ListView):
    model = ShoppingItem
    template_name = "shoppingitems/list.html"
    success_url = reverse_lazy("shopping_list")

    def get_queryset(self):
        return ShoppingItem.objects.filter(user=self.request.user)


@require_http_methods(["POST"])
def ShoppingItemCreate(request):
    ingredient_id = request.POST.get("ingredient_id")
    ingredient = Ingredient.objects.get(id=ingredient_id)
    current_user = request.user

    try:
        ShoppingItem.objects.create(
            user=current_user, food_item=ingredient.food
        )
    except IntegrityError:
        pass

    return redirect("recipe_detail", pk=ingredient.recipe.id)


@require_http_methods(["POST"])
def ShoppingListDelete(request):
    ShoppingItem.objects.filter(user=request.user).delete()
    return redirect("shopping_list")

recipes/templates/recipes/delete.html
{% extends 'base.html' %}

{% block page_name %}
  <title>Delete Recipe - Scrumptious</title>
{% endblock page_name %}

{% block content %}
  <main>
    <form method="post" class="form-text">
      {% csrf_token %}
      <p>Are you sure you want to delete "{{ recipe }}"?</p>
      {{ form.as_p }}
      <div>
        <button class="button">Confirm Delete</button>
      </div>
    </form>
  </main>
{% endblock content %}

recipes/templates/recipes/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% load resizer %}

{% block page_name %}
  <title>Details - Scrumptious</title>
{% endblock page_name %}

{% block content %}
  <main>
    <div class="two-columns">
      <div class = "text-content">
          <!--recipe title-->
          <div class="recipe-name">
              {{ recipe.name }}
          </div>
          <!--rating form-->
          <form method="post" class="rating-form-text" action="{% url 'recipe_rating' recipe.id %}">
              {% csrf_token %}
              {{ rating_form }}
              <button class="button">Rate</button>
          </form>
          <!--tags-->
          <div class="recipe-tags">
              {% for tag in recipe.tags.all %}
                  #{{ tag.name }}
              {% endfor %}
          </div>
          <!--recipe metadata-->
          <div class="date-text">
              created on {{ recipe.created }} | updated on {{ recipe.updated }}<br>
              by {{ recipe.author }}
          </div>
          <!--recipe description-->
          <div class="recipe-description">
              <p>{{ recipe.description }}</p>
          </div>
          <!--edit recipe link and add tags-->
          <span>
            {% if user.username|slugify == recipe.author|slugify %}
              <a href="{% url 'recipe_edit' recipe.id %}" class="edit-recipe-link">Edit this recipe</a>
              &nbsp
              <a href="{% url 'tag_new' %}" class="edit-recipe-link">Add a tag</a>
              &nbsp
              <a href="{% url 'recipe_delete' recipe.id %}" class="edit-recipe-link">Delete this recipe</a>
            {% endif %}
          </span>
          <!--recipe ingredients-->
          <div class="dropdown">
              <input id="check01" type="checkbox" name="Ingredients" class="drop-down-input"/>
              <label for="check01" class="drop-down-label"><h3 class="icon-menu">&nbsp;&nbsp;Ingredients</h3></label>
              <div class="dropdown-content-def-open">
                  <div>
                    Serves {{ recipe.servings }} by default
                    <form method="POST">
                      {% csrf_token %}
                      <label for="serving_scaling">Scale servings to: &nbsp</label>
                      <input name="serving_scaling" type="number" class="serving-scaler" value="{{current_serving_size}}" onchange="this.form.submit()">
                    </form>
                  </div>
                  <table class="ingredients-table">
                    <colgroup>
                      <col style="width: 45%">
                      <col style="width: 35%">
                      <col style="width: 20%">
                    </colgroup>
                    <thead>
                      <tr>
                          <th>Ingredient</th>
                          <th>Amount</th>
                          <th>Add item</th>
                      </tr>
                      </thead>
                      <tbody>
                          {% for ingredient in recipe.ingredients.all %}
                              <tr>
                                  <td>{{ ingredient.food.name }}</td>
                                  <td>{{ ingredient|resize_to:current_serving_size }} {{ ingredient.measure.name }}</td>
                                  <td>
                                    {% if ingredient.food not in shopping_list_foods %}
                                      <form method="POST" action="{% url 'shopping_new' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="ingredient_id" value="{{ ingredient.id }}">
                                        <button title="Add to shopping list" class="shopping-list-button">+</button>
                                      </form>
                                    {% endif %}
                                  </td>
                              </tr>
                          {% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>
          <br>
          <!--recipe steps-->
          <div class="dropdown">
              <input id="check02" type="checkbox" name="Instructions" class="drop-down-input"/>
              <label for="check02" class="drop-down-label"><h3 class="icon-menu">&nbsp;&nbsp;Instructions</h3></label>
              <div class="dropdown-content-def-close">
                  <ol>
                      {% for step in recipe.steps.all %}
                          <li>{{ step.directions }}</li>
                      {% endfor %}
                    <div class="cat-location">
                      <div class="all-wrap">
                        <div class="all">
                          <div class="yarn"></div>
                          <div class="cat-wrap">
                            <div class="cat">
                              <div class="cat-upper">
                                <div class="cat-leg"></div>
                                <div class="cat-leg"></div>
                                <div class="cat-head">
                                  <div class="cat-ears">
                                    <div class="cat-ear"></div>
                                    <div class="cat-ear"></div>
                                  </div>
                                  <div class="cat-face">
                                    <div class="cat-eyes"></div>
                                    <div class="cat-mouth"></div>
                                    <div class="cat-whiskers"></div>
                                  </div>
                                </div>
                              </div>
                              <div class="cat-lower-wrap">
                                <div class="cat-lower">
                                  <div class="cat-leg">
                                    <div class="cat-leg">
                                      <div class="cat-leg">
                                        <div class="cat-leg">
                                          <div class="cat-leg">
                                            <div class="cat-leg">
                                              <div class="cat-leg">
                                                <div class="cat-leg">
                                                  <div class="cat-leg">
                                                    <div class="cat-leg">
                                                      <div class="cat-leg">
                                                        <div class="cat-leg">
                                                          <div class="cat-leg">
                                                            <div class="cat-leg">
                                                              <div class="cat-leg">
                                                                <div class="cat-leg">
                                                                  <div class="cat-paw"></div>
                                                                </div>
                                                              </div>
                                                            </div>
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="cat-leg">
                                    <div class="cat-leg">
                                      <div class="cat-leg">
                                        <div class="cat-leg">
                                          <div class="cat-leg">
                                            <div class="cat-leg">
                                              <div class="cat-leg">
                                                <div class="cat-leg">
                                                  <div class="cat-leg">
                                                    <div class="cat-leg">
                                                      <div class="cat-leg">
                                                        <div class="cat-leg">
                                                          <div class="cat-leg">
                                                            <div class="cat-leg">
                                                              <div class="cat-leg">
                                                                <div class="cat-leg">
                                                                  <div class="cat-paw"></div>
                                                                </div>
                                                              </div>
                                                            </div>
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="cat-tail">
                                    <div class="cat-tail">
                                      <div class="cat-tail">
                                        <div class="cat-tail">
                                          <div class="cat-tail">
                                            <div class="cat-tail">
                                              <div class="cat-tail">
                                                <div class="cat-tail">
                                                  <div class="cat-tail">
                                                    <div class="cat-tail">
                                                      <div class="cat-tail">
                                                        <div class="cat-tail">
                                                          <div class="cat-tail">
                                                            <div class="cat-tail">
                                                              <div class="cat-tail">
                                                                <div class="cat-tail -end"></div>
                                                              </div>
                                                            </div>
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                    </ol>
              </div>
            </div>
      </div>
      <!--recipe image-->
      <div class="image-box">
          {% if recipe.image %}
              <img src="{{ recipe.image }}" class="pull-right img-detail">
          {% endif %}
      </div>
    </div>
  </main>

{% endblock content %}

recipes/templates/recipes/edit.html
{% extends 'base.html' %}

{% block page_name %}
  <title>Edit - Scrumptious</title>
{% endblock page_name %}

{% block content %}

<main>
  <form method="post" class="form-text" autocomplete="off">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button class="button">Edit Recipe</button>
      </div>
  </form>
</main>

{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'base.html' %}

{% block page_name %}
  <title>Scrumptious</title>
{% endblock page_name %}

{% block content %}
  <main>
    <div class="pagination padded">
      <form method="POST">
        {% csrf_token %}
        <label for="sort_type">Sort by: </label>
        <select name="sort_type" onchange="this.form.submit()" class="sorting-select">
          <option>Select</option>
          <option value="-updated">Last updated</option>
          <option value="-created">Last created</option>
          <option value="name">Name</option>
          <option value="author">Author</option>
        </select>
      </form>
      {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="unstyle-link">&#x25C0 &nbsp</a>
      {% endif %}
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="unstyle-link">&nbsp &#x25B6</a>
      {% endif %}
    </div>
    <div class="main-page-gallery">
      {% for recipe in recipe_list %}
          <a href="{% url 'recipe_detail' recipe.pk %}" class="card-a">
              <div class="recipe-card">
                  <h2 class="recipe-card-title">
                      {{ recipe.name }}
                  </h2>
                  {% if recipe.image %}
                      <img src="{{ recipe.image }}" class="pull-right card-img-detail">
                  {% endif %}
                  <span class="recipe-card-date">{{ recipe.updated }}</span>
                  <div class="recipe-tags">
                    {% for tag in recipe.tags.all %}
                        #{{ tag.name }}
                    {% endfor %}
                  </div>
              </div>
          </a>
      {% endfor %}
    </div>
  </main>
{% endblock content %}

recipes/templates/recipes/new.html
{% extends 'base.html' %}

{% block page_name %}
  <title>New Recipe - Scrumptious</title>
{% endblock page_name %}

{% block content %}
  <main>
    <form method="post" class="form-text" autocomplete="off">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
          <button class="button">Create</button>
        </div>
    </form>
  </main>
{% endblock content %}