recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    log_rating,
    RecipeDetailView,
    RecipeListView,
    ShoppingListView,
    ShoppingItemCreate,
    ShoppingListDelete,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path("shopping_items/", ShoppingListView.as_view(), name="shopping_list"),
    path("shopping_items/create/", ShoppingItemCreate, name="shopping_new"),
    path("shopping_items/delete/", ShoppingListDelete, name="shopping_delete"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("mealplans/", include("mealplans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

mealplans/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class MealPlan(models.Model):
    name = models.CharField(max_length=125)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="mealplans",
        on_delete=models.CASCADE,
        null=True,
    )
    description = models.TextField()
    startdate = models.DateField(null=True)
    recipes = models.ManyToManyField(
        "recipes.Recipe",
        related_name="meal_plans",
        blank=True,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

recipes/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL,
        related_name="recipes",
        on_delete=models.CASCADE,
        null=True,
    )
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    servings = models.PositiveSmallIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(100),
        ]
    )

    def __str__(self):
        return self.name + " by " + str(self.author)


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField(validators=[MaxValueValidator(9999)])
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ingredients",
        on_delete=models.CASCADE,
    )
    measure = models.ForeignKey("Measure", on_delete=models.PROTECT)
    food = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def __str__(self):
        amount = str(self.amount)
        measure = self.measure.name
        food = self.food.name
        return amount + " " + measure + " " + food


class Step(models.Model):
    recipe = models.ForeignKey(
        "Recipe",
        related_name="steps",
        on_delete=models.CASCADE,
    )
    order = models.PositiveSmallIntegerField()
    directions = models.CharField(max_length=300)
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return str(self.order) + ". " + self.directions


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ratings",
        on_delete=models.CASCADE,
    )


class ShoppingItem(models.Model):
    user = models.ForeignKey(
        USER_MODEL,
        related_name="ShoppingItem",
        on_delete=models.CASCADE,
        null=True,
    )
    food_item = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def __str__(self):
        return str(self.food_item) + " for " + str(self.user)

recipes/forms.py
from django import forms
from recipes.models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "name",
            "author",
            "description",
            "image",
        ]


from recipes.models import Rating


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]

recipes/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.db import IntegrityError

from recipes.forms import RatingForm
from recipes.models import Recipe, ShoppingItem, Ingredient

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods


def log_rating(request, recipe_id):
    try:
        if request.method == "POST":
            form = RatingForm(request.POST)
            if form.is_valid():
                rating = form.save(commit=False)
                rating.recipe = Recipe.objects.get(pk=recipe_id)
                rating.save()
    except Recipe.DoesNotExist:
        return redirect("recipes_list")
    return redirect("recipe_detail", pk=recipe_id)


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 6
    sort_method = "-updated"

    def post(self, request):
        self.sort_method = request.POST.get("sort_type")
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_queryset(self):
        return Recipe.objects.order_by(self.sort_method)


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"
    current_serving_size = Recipe.servings

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()

        shopping_items = [
            item.food_item for item in self.request.user.ShoppingItem.all()
        ]

        context["shopping_list_foods"] = shopping_items
        context["current_serving_size"] = Recipe.servings

        return context

    def post(self, request, **kwargs):
        self.current_serving_size = request.POST.get("serving_scaling")
        self.object = self.get_object()
        context = self.get_context_data(**kwargs)
        context["current_serving_size"] = self.current_serving_size
        return self.render_to_response(context)


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = ["name", "description", "image", "servings"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = ["name", "description", "image", "servings"]

    def get_success_url(self):
        recipeid = self.kwargs["pk"]
        return reverse_lazy("recipe_detail", kwargs={"pk": recipeid})

    def get_queryset(self):
        return Recipe.objects.filter(author=self.request.user)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")

    def get_queryset(self):
        return Recipe.objects.filter(author=self.request.user)


class ShoppingListView(LoginRequiredMixin, ListView):
    model = ShoppingItem
    template_name = "shoppingitems/list.html"
    success_url = reverse_lazy("shopping_list")

    def get_queryset(self):
        return ShoppingItem.objects.filter(user=self.request.user)


@require_http_methods(["POST"])
def ShoppingItemCreate(request):
    ingredient_id = request.POST.get("ingredient_id")
    ingredient = Ingredient.objects.get(id=ingredient_id)
    current_user = request.user

    try:
        ShoppingItem.objects.create(
            user=current_user, food_item=ingredient.food
        )
    except IntegrityError:
        pass

    return redirect("recipe_detail", pk=ingredient.recipe.id)


@require_http_methods(["POST"])
def ShoppingListDelete(request):
    ShoppingItem.objects.filter(user=request.user).delete()
    return redirect("shopping_list")

recipes/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block page_name %}
  {% endblock page_name %}
  <link rel="stylesheet" href="{% static 'css/cat.css' %}">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
</head>
<body>
    <div class="banner">
        <!--Adjust banner-->
        <img src="https://i.imgur.com/8m2emSJ.png">
    </div>
    <header class="cd-header">
        <div class="header-wrapper">
            <div class="nav-but-wrap">
                <div class="menu-icon hover-target">
                    <span class="menu-icon__line menu-icon__line-left"></span>
                    <span class="menu-icon__line"></span>
                    <span class="menu-icon__line menu-icon__line-right"></span>
                </div>
                <div class="menu-text">
                    Menu
                </div>
            </div>
        </div>
        <div class="switch-wrap">
            <div id="switch" class="hover-target">
                <div id="circle"></div>
            </div>
            <div>
                <div class="switch-text-dark">
                dark
                </div>
                <div class="switch-text-light">
                    light
                </div>
            </div>
        </div>
    </header>
    <div class="header-backdrop">
    </div>
    <div class="nav">
        <div class="nav__content">
            <ul class="nav__list">
                <!-- change active nav to current page by changing class="nav_list-item active-nav"-->
                <li class="nav__list-item"><a href="{% url 'home' %}" class="hover-target">Home</a></li>
                {% if user.is_authenticated %}
                    <li class="nav__list-item"><a href="{% url 'mealplan_list' %}" class="hover-target">Meal Plans</a></li>
                    <li class="nav__list-item"><a href="{% url 'tags_list' %}" class="hover-target">Tags</a></li>
                    <li class="nav__list-item"><a href="{% url 'recipe_new' %}" class="hover-target">Add a Recipe</a></li>
                    <li class="nav__list-item"><a href="{% url 'mealplan_new' %}" class="hover-target">Add a Meal Plan</a></li>
                    <li class="nav__list-item"><a href="{% url 'shopping_list' %}" class="hover-target">View Shopping List</a></li>
                    {% if user.is_staff %}
                        <li class="nav__list-item"><a href="{% url 'admin:index' %}" class="hover-target">Admin</a></li>
                    {% endif %}
                    <li class="nav__list-item"><a href="{% url 'logout' %}" class="hover-target">Log Out</a></li>
                {% endif %}
                {% if user.is_authenticated == False %}
                    <li class="nav__list-item"><a href="{% url 'login' %}" class="hover-target">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>

    {% block content %}
    {% endblock content %}

    <footer>
        <a href="{% url 'home' %}" class="link-to-page" target=”_blank”></a>
    </footer>
    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
</body>

</html>

recipes/templates/cat.html
{% extends 'base.html' %}

{% block unleashthecat %}
<div class="all-wrap">
    <div class="all">
      <div class="yarn"></div>
      <div class="cat-wrap">
        <div class="cat">
          <div class="cat-upper">
            <div class="cat-leg"></div>
            <div class="cat-leg"></div>
            <div class="cat-head">
              <div class="cat-ears">
                <div class="cat-ear"></div>
                <div class="cat-ear"></div>
              </div>
              <div class="cat-face">
                <div class="cat-eyes"></div>
                <div class="cat-mouth"></div>
                <div class="cat-whiskers"></div>
              </div>
            </div>
          </div>
          <div class="cat-lower-wrap">
            <div class="cat-lower">
              <div class="cat-leg">
                <div class="cat-leg">
                  <div class="cat-leg">
                    <div class="cat-leg">
                      <div class="cat-leg">
                        <div class="cat-leg">
                          <div class="cat-leg">
                            <div class="cat-leg">
                              <div class="cat-leg">
                                <div class="cat-leg">
                                  <div class="cat-leg">
                                    <div class="cat-leg">
                                      <div class="cat-leg">
                                        <div class="cat-leg">
                                          <div class="cat-leg">
                                            <div class="cat-leg">
                                              <div class="cat-paw"></div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="cat-leg">
                <div class="cat-leg">
                  <div class="cat-leg">
                    <div class="cat-leg">
                      <div class="cat-leg">
                        <div class="cat-leg">
                          <div class="cat-leg">
                            <div class="cat-leg">
                              <div class="cat-leg">
                                <div class="cat-leg">
                                  <div class="cat-leg">
                                    <div class="cat-leg">
                                      <div class="cat-leg">
                                        <div class="cat-leg">
                                          <div class="cat-leg">
                                            <div class="cat-leg">
                                              <div class="cat-paw"></div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="cat-tail">
                <div class="cat-tail">
                  <div class="cat-tail">
                    <div class="cat-tail">
                      <div class="cat-tail">
                        <div class="cat-tail">
                          <div class="cat-tail">
                            <div class="cat-tail">
                              <div class="cat-tail">
                                <div class="cat-tail">
                                  <div class="cat-tail">
                                    <div class="cat-tail">
                                      <div class="cat-tail">
                                        <div class="cat-tail">
                                          <div class="cat-tail">
                                            <div class="cat-tail -end"></div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock unleashthecat %}